/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GovernanceIndexRouteImport } from './routes/governance.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as GovernanceSlugRouteImport } from './routes/governance.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceSlugRoute = GovernanceSlugRouteImport.update({
  id: '/governance/$slug',
  path: '/governance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/blog': typeof BlogIndexRoute
  '/governance': typeof GovernanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/blog': typeof BlogIndexRoute
  '/governance': typeof GovernanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/governance/$slug': typeof GovernanceSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/governance/': typeof GovernanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/$slug' | '/governance/$slug' | '/blog' | '/governance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/governance/$slug' | '/blog' | '/governance'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/governance/$slug'
    | '/blog/'
    | '/governance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GovernanceSlugRoute: typeof GovernanceSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/$slug': {
      id: '/governance/$slug'
      path: '/governance/$slug'
      fullPath: '/governance/$slug'
      preLoaderRoute: typeof GovernanceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  GovernanceSlugRoute: GovernanceSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
