name: janus

services:
  postgres:
    image: postgres
    container_name: janus-postgres
    environment:
      POSTGRES_DB: janus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /opt/janus/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  janus_postgres_data:
